### PR TITLE
Split large batches

### LINKED ISSUE #30: Manticore::SocketException / Broken pipe
We use your plugin for a big volume of logs. We note that it is not stable. After some hours, we get some errors like the following and the service get stuck despite that logstash status is green. The restart of logstash correct the problem.

[2023-09-11T09:16:58,461][ERROR][logstash.outputs.dynatrace][main][logstash_output] Could not fetch URL {:ingest_endpoint_url=>"https://##DYN_TENANT##.live.dynatrace.com/api/v2/logs/ingest", :message=>"Broken pipe", :class=>Manticore::SocketException, :will_retry=>true}

the pipeline is like this
```
    input {
      file {
        path => "/share/logs/**/*.log"
        sincedb_path => "/usr/share/logstash/data/file-sincedb.db"
        start_position => end
        mode => "tail"

        codec => multiline {
          pattern => "^\[[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3} GMT\] "
          negate => true
          what => "previous"
        }
      }
    }
    filter{
      mutate {
        replace => [ "host", "logstash-prod" ]
      }
      grok {
          match => [ "[@metadata][path]" ,"%{GREEDYDATA:log.source}"]
      }
    }
    output {
      dynatrace {
        id => "logstash_output"
        ingest_endpoint_url => "https://xxxxxx.live.dynatrace.com/api/v2/logs/ingest"
        api_key => "xxxxxx"
      }
    }
```

Expected:
We would like that the service get not stuck and manage socket correctly

Versions:
-Logstash is running on kubernetes. The logstash image is docker.elastic.co/logstash/logstash:8.5.1.
-The plugin of logstash-output-dynatrace is 0.5.0. Logstash is running in a statefulset mode. 
-The env var LS_JAVA_OPTS is set with "-Xmx11g -Xms11g" and the statefulset ressources is defined like this
```
        resources:
          requests:
            cpu: "5"
            memory: 15Gi
          limits:
            cpu: "5"
            memory: 15Gi
```
Additionnal information:
Note that when the service logstash is stuck with a lot of error "Could not fetch URL ", a curl command on the logstash running pod could be done on the same target "https://xxxxxx.live.dynatrace.com/api/v2/logs/ingest" without http error code. And, the log injected with curl could be seen on dynatrace dashboard.

### PR DESCRIPTION
**Pull request by dyladan**
Fixes #30 

Splits batches of events larger than 4.5MB into multiple requests in order to stay under the 5MB API limit.

Introduces a `Batcher` component which builds batches and counts the size of the resulting request body. The `offer` method returns `true` if the event is accepted as a part of the current batch or `false` if the event would make the batch too large. `drain_and_serialize` returns a JSON string request body for export and clears the array.

### CODE REVIEW

File: lib/logstash/outputs/dynatrace.rb [hunk 1]
```diff
@@ -74,6 +74,9 @@ class PluginInternalQueueLeftoverError < StandardError; end
       # Include body in debug logs when HTTP errors occur. Body may be large and include sensitive data.
       config :debug_include_body, validate: :boolean, default: false
 
+      # Maximum size payload to send to the Dynatrace API. Batches of events which would be larger than max_payload_size when serialized will be split into smaller batches of events.
```
Comment (dyladan) [inline lib/logstash/outputs/dynatrace.rb:77]: Is this something we want to make configurable or should we make it constant? Making it configurable means users could change it if the Dynatrace API limits change without having to wait for us to release

File: lib/logstash/outputs/dynatrace.rb [hunk 2]
```diff
@@ -103,6 +106,40 @@ def run
...
+          if batch_size + serialized_event.length + (@serialized_events.length.positive? ? 1 : 0) > @max_batch_size
+            return false
+          end
+
+          @serialized_events.push(serialized_event)
+          @batch_events_size += serialized_event.length
+          true
+        end
+
+        def batch_size
```
Comment (arminru) [inline lib/logstash/outputs/dynatrace.rb:127]: This sounds like the number of items in the batch, maybe call it `batch_wire_size` or `batch_size_serialized` or something like that.

File: lib/logstash/outputs/dynatrace.rb [hunk 3]
```diff
@@ -199,11 +248,10 @@ def sleep_for_attempt(attempt)
       end
 
       def send_event(event, attempt)
```
Comment (arminru) [inline lib/logstash/outputs/dynatrace.rb:250]: This is not actually one event but rather a serialized batch of events, right?

File: spec/outputs/dynatrace_spec.rb [hunk 4]
```diff
@@ -186,6 +186,17 @@
         expect(subject).to have_received(:send_event).exactly(3).times
       end
     end
+
+    context 'with more than 4.5MB of events' do
+      before do
+        allow(subject).to receive(:send_event) { |e, att| [:success, e, att] }
+        subject.multi_receive([*1..2].map { |n| LogStash::Event.new({ 'n' => n.to_s * 2_500_001 }) })
```
Comment (arminru) [inline spec/outputs/dynatrace_spec.rb:193]:
```suggestion
        subject.multi_receive([1,2].map { |n| LogStash::Event.new({ 'n' => n.to_s * 2_500_001 }) })
```
This would do the same, right?

File: spec/outputs/dynatrace_spec.rb [hunk 5]
```diff
@@ -186,6 +186,17 @@
         expect(subject).to have_received(:send_event).exactly(3).times
       end
     end
+
+    context 'with more than 4.5MB of events' do
```
Comment (arminru) [inline spec/outputs/dynatrace_spec.rb:190]: Please also add a test for handling:

- one event < 4.5 MB followed by an event > 4.5 MB
- one event > 4.5 MB followed by an event < 4.5 MB

You could also consider adding a third test that shows that configuring `max_payload_size` to a different value has the expected effect.

File: lib/logstash/outputs/dynatrace.rb [hunk 6]
```diff
@@ -103,6 +106,40 @@ def run
...
+
+        def offer(event)
+          serialized_event = LogStash::Json.dump(event.to_hash)
+          if batch_size + serialized_event.length + (@serialized_events.length.positive? ? 1 : 0) > @max_batch_size
+            return false
+          end
+
+          @serialized_events.push(serialized_event)
+          @batch_events_size += serialized_event.length
+          true
```
[the remark this answers is not in the document]
Comment (dyladan) [reply lib/logstash/outputs/dynatrace.rb:124]: The linter reverts this change automatically. It's a common ruby construct. The return statement is required above because it cannot be an implicit return

File: version.yaml [hunk 7]
```diff
@@ -1 +1 @@
-logstash-output-dynatrace: '0.5.0'
+logstash-output-dynatrace: '0.5.1'
```
[the remark this answers is not in the document]
Comment (dyladan) [reply version.yaml:1]: In semver the third number is treated as the minor version. This is not a breaking change.

File: lib/logstash/outputs/dynatrace.rb (hunk 3 above)
Comment (dyladan) [reply lib/logstash/outputs/dynatrace.rb:246]: Yes. It was before too actually. I didn't rename it because it came from the upstream http plugin and I wanted to keep them as similar as possible in case there were questions later and someone had to refer to the upstream code.

File: version.yaml (hunk 7 above)
[the remark this answers is not in the document]
Comment (arminru) [reply version.yaml:1]: Fine with me then!

File: lib/logstash/outputs/dynatrace.rb (hunk 3 above)
Comment (arminru) [reply lib/logstash/outputs/dynatrace.rb:250]: Good point, then it's better to stay in sync with them, yeah. Thanks!

File: spec/outputs/dynatrace_spec.rb (hunk 5 above)
Comment (arminru) [reply spec/outputs/dynatrace_spec.rb:191]: Would the last suggestion - a test for the config itself - be easy to implement?

File: lib/logstash/outputs/dynatrace.rb [hunk 8]
```diff
@@ -106,28 +106,23 @@ def run
...
         end
 
-        def offer(event)
-          serialized_event = LogStash::Json.dump(event.to_hash)
-          if batch_size + serialized_event.length + (@serialized_events.length.positive? ? 1 : 0) > @max_batch_size
-            return false
-          end
+        def offer(serialized_event)
+          # 2 square brackets, the length of all previously serialized strings, commas, and the current event size
+          batch_size_bytes = 2 + @batch_events_size + @serialized_events.length + serialized_event.length
```
Comment (arminru) [inline lib/logstash/outputs/dynatrace.rb:118]: Should this be serialized_events.length-1 since there is no comma after the last entry?

**Review by arminru — APPROVED** [review]

File: lib/logstash/outputs/dynatrace.rb (hunk 8 above)
Comment (dyladan) [reply lib/logstash/outputs/dynatrace.rb:118]: this is the count of previously serialized events, which is actually the correct count of commas when the new event is added. The `-1`s and `+1`s of the previous version cancelled each other out.

1. first event is added. serialized events is 0 and 0 commas are in the output
2. second event is added. serialized events is 1 and 1 comma is added
3. and so on

File: spec/outputs/dynatrace_spec.rb (hunk 5 above)
Comment (dyladan) [reply spec/outputs/dynatrace_spec.rb:191]: maybe. i'll give it a go
